### ISSUE TITLE
Scrollbar showing constantly

### ISSUE THREAD

**Issue by i386sh** [lwouis/alt-tab-macos#196]
![image](https://user-images.githubusercontent.com/24914325/78113772-f7623880-744b-11ea-92ed-add1b6e715b4.png)

Opened it for the first time; pressed alt-tab to see if it worked, saw that.
No amount of configuring fixes it.

__Debug profile:__

* App version: 3.2.1
* App preferences: 
  * SUHasLaunchedBefore: Optional(1)
  * SULastCheckTime: Optional(2020-04-01 08:03:51 +0000)
  * alignThumbnails: Optional(Center)
  * fontHeight: Optional(15)
  * hideSpaceNumberLabels: Optional(false)
  * iconSize: Optional(19)
  * maxCellsPerRow: Optional(13)
  * maxScreenUsage: Optional(80)
  * metaKey: Optional(⌥ option)
  * minCellsPerRow: Optional(5)
  * rowsCount: Optional(5)
  * showOnScreen: Optional(Screen including mouse)
  * startAtLogin: Optional(false)
  * tabKeyCode: Optional(48)
  * theme: Optional( macOS)
  * windowDisplayDelay: Optional(0)
* Applications count: 36
* Windows: 
  * {isMinimized: false, isHidden: false, isOnAllSpaces: false, spaceId: 1, spaceIndex: 1}
  * {isMinimized: false, isHidden: false, isOnAllSpaces: false, spaceId: 1, spaceIndex: 1}
  * {isMinimized: false, isHidden: false, isOnAllSpaces: false, spaceId: 1, spaceIndex: 1}
  * {isMinimized: false, isHidden: false, isOnAllSpaces: false, spaceId: 1, spaceIndex: 1}
  * {isMinimized: true, isHidden: false, isOnAllSpaces: false, spaceId: 1, spaceIndex: 1}
  * {isMinimized: false, isHidden: false, isOnAllSpaces: false, spaceId: 1, spaceIndex: 1}
* OS version: Version 10.13.6 (Build 17G66)
* OS architecture: x86_64
* Locale: en_AU (current)
* Spaces count: 1
* Hardware model: MacBookPro8,1
* Displays count: 1
* CPU model: Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
* Memory size: 17.18 GB
* Active CPU count: 4
* Current CPU frequency: 2.4 Ghz

**Comment by lwouis** [comment]
Hi @i386sh! Thanks for sharing this issue!

Could you please click the "Send Feedback" within the app:

![image](https://user-images.githubusercontent.com/106195/78120687-540e2500-7445-11ea-84da-93055ea2ff5a.png)

This will open a ticket here and it will attach very helpful debug information such as the version of macOS you are running. Indeed, this scrollbar doesn't show for me and other people, so it must be about something specific to your environment. Opening a ticket from the app will help us investigate what could be at play here :)

**Comment by i386sh** [comment]
I sent a feedback request. I didn't include an email. I hope that's okay.

**Comment by lwouis** [comment]
Thanks! I added the debug profile to this ticket here

**Comment by lwouis** [comment]
I suspect it could be an issue with macOS 10.13.6. It would be nice if someone could either reproduce there, and share with us that is works for them under 10.13. Nobody else seems to see this visual artifact under 10.14 and 10.15.

**Comment by i386sh** [comment]
I mean that's definitely a possibility.
I might use the Mojave patcher from dosdude1, to install Mojave on my machine to see if it works fine under 10.14.

**Comment by lwouis** [comment]
Oh wow, your hardware doesn't support official updates? It's from 2011, that's pretty cool that you're still getting good usage out of it 👍

At least to reproduce the issue to potentially fix it, I'm thinking about using a VM in VirtualBox. There are some images available online of macOS older releases. It's a bit involved so I haven't found time to do it yet though

**Comment by buttercrab** [comment]
![image](https://user-images.githubusercontent.com/34997549/78760678-7a3f4200-79bc-11ea-97f2-49f89091ee3d.png)
I think this is similar issue. I'm running on MacOS 10.15.

**Comment by lwouis** [comment]
@buttercrab does it happen all the time? On your screenshot you seem to have only 1 window displayed. Does it happen with more windows? Does it happen with a *lot* of windows, like 40? (this is where the scrollbar is supposed to show).

This is very weird that it doesn't do it on my machine which is also 10.15. The good news is that I don't need a VM to try to reproduce now. The bad news is I have no clue why this is happening on some machines

**Comment by buttercrab** [comment]
| Lots of Tabs | Two rows | Three rows |
|---|---|---|
|![image](https://user-images.githubusercontent.com/34997549/78779934-cd26f280-79d8-11ea-9b96-50128b044b91.png)|![image](https://user-images.githubusercontent.com/34997549/78779981-e039c280-79d8-11ea-95c8-271a340201cb.png)|![image](https://user-images.githubusercontent.com/34997549/78780006-ea5bc100-79d8-11ea-8024-c195b9170ccd.png)|

Yeap. It always shows up. I think any settings would make it show up.
_BTW, They are Korean_

**Comment by lwouis** [comment]
Aaah! I found how to reproduce the issue! I noticed on one of your thumbnails, the System Preferences was in Dark Mode. I switched to Dark Mode and now I see the light vertical bar.

@i386sh are you also using Dark Mode? I don't know if they retro-fit the feature on 10.13 or if it's exclusive to 10.15+. If it's not the case, then we should make a new, different ticket for Dark Mode on 10.15.

**Comment by buttercrab** [comment]
Great! I hope this fix will be included in the next update.

**Comment by lwouis** [comment]
@buttercrab I need to find how to fix this first! It's another undocumented behavior from Apple `NSScrollView`. I thought I fixed it by overriding this method:

https://github.com/lwouis/alt-tab-macos/blob/master/src/ui/main-window/ThumbnailsView.swift#L97

Apparently I need to find another implementation-details workaround

**Comment by i386sh** [comment]
> Aaah! I found how to reproduce the issue! I noticed on one of your thumbnails, the System Preferences was in Dark Mode. I switched to Dark Mode and now I see the light vertical bar.
> 
> @i386sh are you also using Dark Mode? I don't know if they retro-fit the feature on 10.13 or if it's exclusive to 10.15+. If it's not the case, then we should make a new, different ticket for Dark Mode on 10.15.

I still haven't updated to Mojave. Been lazy. But I'm using the semi-dark theme (dock + menubar), if that counts?

**Comment by lwouis** [comment]
> But I'm using the semi-dark theme (dock + menubar)

What is this exactly? Could you show me screenshots of how this is configured? This is how dark mode looks in System Preferences > General, in Catalina:

![image](https://user-images.githubusercontent.com/106195/78790529-9dccb180-79e9-11ea-8a4c-d7725b916cac.png)

> Updated and now I can't launch alt-tab.

Could you please type this in a terminal and show us the result?

```bash
defaults read com.lwouis.alt-tab-macos
```

This is for me to understand better what crashes. After sharing that info, I think you will be unstuck if you type this command and start AltTab again:

```bash
defaults delete com.lwouis.alt-tab-macos
```

**Comment by lwouis** [comment]
@i386sh I release a hotfix which will hopefully fix the crash at startup

**Comment by i386sh** [comment]
![image](https://user-images.githubusercontent.com/24914325/78822520-91af1700-7a1e-11ea-9ea1-ee8f6425e7ce.png)
Unfortunately, my issue still isn't solved though.

![image](https://user-images.githubusercontent.com/24914325/78822546-9c69ac00-7a1e-11ea-83c9-9c5fc69d5a09.png)
By half-dark mode I mean this.

I will be installing Mojave later today, so I will see if that will solve my issue.

**Comment by lwouis** [comment]
> Unfortunately, my issue still isn't solved though.

This is with the latest version, 3.7.1? I'm really surprised that it's not fixed. It really looks like the scrollbar is the `.legacy` style, always showing, and having a background.

I guess it's back to running a VM to reproduce.

**Comment by buttercrab** [comment]
Mine either. 3.7.x didn't solved the issue.

**Comment by lwouis** [comment]
I was able to reproduce! Not only was there an issue with Dark Mode, but there is a second layer of interaction with this setting:

![image](https://user-images.githubusercontent.com/106195/78856341-774a5d00-7a61-11ea-9b07-056fbb993b69.png)

**Comment by i386sh** [comment]
Setting it to _When scrolling_ seems to fix the issue for me.

Not bothered by the fact I only see scrollbars when scrolling.

**Comment by lwouis** [comment]
When selecting "Always", the OS forces all scroller to be of style `.legacy`. I can't find any way to not be affected by this. Finding info on this is a nightmare

**Comment by lwouis** [comment]
@i386sh and @buttercrab I released a new version that should have the scrollbar properly show whichever dark mode and scrollbar style preferences you set. Could you please let me know if it's working good with all of the possible settings for you? I'll re-open the ticket if something is still wrong for you :)

**Comment by buttercrab** [comment]
Great! It's working perfectly.

**Comment by i386sh** [comment]
Hoorah! All is good!

**Comment by spunti** [comment]
Problem is fixed! Thank you!!
