### ISSUE TITLE
icons filcker

### ISSUE THREAD

**Issue by ForsakenDelusion** [lwouis/alt-tab-macos#4035]
**Describe the bug**

When I press the key to bring up the window switcher, the icons of the hidden applications will tremble/flicker.
**Screenshots / video**

https://github.com/user-attachments/assets/028458cb-c782-4b88-bad9-4605a14079fa

**Steps to reproduce the bug**

alt + tab when some app were hidden

**Your environment**

* AltTab version: 7.14.1
* macOS version: 15.1
* Other relevant info: e.g. using external keyboard, multiple monitors, etc
I Use the 2k display, and use https://github.com/xzhih/one-key-hidpi to open the hidip on my 2k monitor.I don't know if this has any impact.

And  only one app is running.
<img width="784" alt="image" src="https://github.com/user-attachments/assets/f3d63471-98ce-4603-ba87-c74331e2e5b1" />

**Comment by lwouis** [comment]
Hi,

Thank you for sharing this issue

It looks like the icon is loading in low-resolution first, then in HD:

First | Then
-|-
![image](https://github.com/user-attachments/assets/bc8f0868-7fc8-4c19-aea0-6ccc5b817ff5) | ![image](https://github.com/user-attachments/assets/3caff7d6-4f55-4512-af2d-3fd35953efd4)

**Comment by ForsakenDelusion** [comment]
Thank you very much for your reply. Your comment made me notice this issue, so I adjusted the resolution back to the original setting, and the bug disappeared with it. I should have thought of testing this way earlier, and I'm very sorry for the additional work it has caused you. Could this be an upstream issue? I'm not sure if pressing ALT+TAB will solve the problem. Once again, thank you for your valuable contribution.

**Comment by lwouis** [comment]
Thank you for your message

> I adjusted the resolution back to the original setting

What is the exact change you made? Screen resolution? From which value to which value?

I think there may be improvements to be made in AltTab here. AltTab correctly identifies the right resolution to display in. It does it in front of the user. I think we should find a way to make that choice before showing the UI.

My issue is that I've never seen this issue in 5 years of this project. This is the first time someone reports it. I can't reproduce it myself. I'm unsure how it's possible that the image view thinks it's in such a low-resolution initially.

Could you please share more about your resolution, DPI, and if you used 1 or multiple monitor and moved the AltTab window from one to the other? Perhaps changes from a monitor to another are responsible here?

Thank you 🙇

**Comment by ForsakenDelusion** [comment]
https://github.com/user-attachments/assets/acef1e87-3c9c-4b7c-ac01-f8b79e19adbe




I hope this video clearly shows all the changes I've made. When i use HIDPI,almost every time I encounter this issue, but when I revert to the default resolution, everything works fine (note that the first time calling alttab after switching back from HIDPI to the default resolution, the icon flickering problem still occurs, but I believe this is just a normal phenomenon following the resolution switch, and it won't happen again in subsequent uses. I hope I've described it clearly.）I'm using a single monitor and only have one window space. However, there's something to note: Apple's support for 2K monitors in HIDPI is not ideal. So, I used this project: https://github.com/xzhih/one-key-hidpi. I saw in it that it mentioned, "The logo scaling may not work because the high resolution is fake." Could this be the problem? But I think the "logo" here refers to the Apple logo on the Mac startup, not the app icon. However, there might be some connection between the two, so I'm reporting this situation to you. Thank you very much for your attention to this issue.

**Comment by lwouis** [comment]
Thank you for your message

I'm using [BetterDisplay Pro](https://github.com/waydabber/BetterDisplay#readme) to have HiDPI resolution on my Dell external monitor. I think I addressed the same problem you faced, having a non-Apple external display, and wanting crisp resolution on it.

Could you please try out BetterDisplay Pro, and see if you still face the issue with this tool, instead of one-key-hidpi? I'm wondering if the issue you experienced could be due to the tool doing something a bit exotic, or not.

If you can reproduce the issue with BetterDisplay Pro instead of one-key-hidpi, I think it will confirm that there is an issue with AltTab.

Thank you

**Comment by ForsakenDelusion** [comment]
Unfortunately, the issue seems to have become more apparent😿.


https://github.com/user-attachments/assets/76ae5bc4-f6ff-4191-be05-1d0b4e662f32

**Comment by ForsakenDelusion** [comment]
> Unfortunately, the issue seems to have become more apparent😿.不幸的是，这个问题似乎变得更加明显了😿。
> 
>  2024-12-31.02-13-41.mov

In the next two days, I'll try to install BetterDisplay Pro on a new macOS to test it and hope my test results will be helpful in locating the bugs. But for now, I've got to worry about my final exam tomorrow 😵‍💫. Thank you for your attention to the issue, and I wish you a wonderful day.

**Comment by lwouis** [comment]
Thank you @ForsakenDelusion
I hope your exam went well!
Thank you for your help resolving this issue 🙇

**Comment by ForsakenDelusion** [comment]
Thank you very much!  😇
I tested on the same machine using the new macOS 15.2 with factory settings., and everything worked perfectly Alt-Tab functioned without any issues. I believe the problem was likely caused by that plugin faking some kind of resolution.

**Comment by ForsakenDelusion** [comment]
Just now, I upgraded to the latest 7.16.0 version, and was surprised to find that the icon blinking issue seems to have disappeared on my device. However, there's a new problem with the icons. Under certain conditions, the icons shrink and move to the upper left corner. I hope my video description clearly explains this issue.

https://github.com/user-attachments/assets/1e73b2e6-8f20-40c3-a933-96b6d982cc7c

**Comment by lwouis** [comment]
Hi @ForsakenDelusion,

Thank you for sharing. These images are hard to nail down. I found a [good article that helped me understand more](https://www.noodlesoft.com/blog/2011/04/15/the-proper-care-and-feeding-of-nsimage/). I've tried to copy() images instead of sharing them. In my tests locally, it works very well.

Could you [please try out this local build](https://github.com/user-attachments/files/18310930/AltTab.app.zip) and let me know if the flickering happens (I'm not sure about this), and it the app icons are broken or not?

Thank you!

**Comment by lwouis** [comment]
@ForsakenDelusion actually, I just released a new public version. Could you please try it out?
Thank you 🙇

**Comment by ForsakenDelusion** [comment]
@lwouis Hi,I haven't checked my messages promptly in the past two days, and I apologize for that🙇. I tested the latest version 7.18 up to now, as well as version 7.17 and your local build version, and ultimately found that the issue of icon flickering still persists. Only in version 7.16 did the problem of icon flickering change to the icon shrinking to the top-left corner when the application is hidden.Just like the situation mentioned in the video I sent in the previous comment above.
Thank you !😊

**Comment by ForsakenDelusion** [comment]
Adding a point I've been overlooking until now—it seems that only Safari and Edge browsers experience icon flickering 🤔. I haven't noticed this issue with more software in use yet.

**Comment by lwouis** [comment]
Hi,

Could you [please try out the build shared here](https://github.com/lwouis/alt-tab-macos/issues/4194#issuecomment-2635217331)? I think it may resolve this issue as well

Thank you

**Comment by ForsakenDelusion** [comment]
> Hi,
> 
> Could you [please try out the build shared here](https://github.com/lwouis/alt-tab-macos/issues/4194#issuecomment-2635217331)? I think it may resolve this issue as well
> 
> Thank you

Hi，Thank you for your long-term dedication to this issue.🧎
I will try it in the coming two days.Beacuase i did`t bring my monitor back during the Spring festival.I will reply to you as soon as possible after trying out the new version.😊

**Comment by ForsakenDelusion** [comment]
@lwouis Hi ! Based on initial observations, it runs exceptionally well.!!! I am genuinely happy about this ,Thank you so much ! I'll continue monitoring its performance and provide further feedback.

**Comment by lwouis** [comment]
Hi @ForsakenDelusion,

Could you please let me know if the latest release fixes this issue for you?

Thank you 🙇

**Comment by ForsakenDelusion** [comment]
@lwouis Hi！
Yes!This problem has been perfectly solved, thank you for your efforts!You are a very nice and kind person, have a wonderful day!!
I'm not sure if I should close the issue because I'm not sure if it will hinder your work, so I'm keeping it as is for now.🙇
Thank you !

**Comment by lwouis** [comment]
Thank you for your kindness~
